### ISSUE TITLE
How to use custom wmts as basemap ?

### ISSUE THREAD

**Issue by iwaitu** [Esri/arcgis-maps-sdk-unreal-engine-samples#16]
How to use custom wmts as basemap ?

**Comment by Jade-JadeH** [comment]
> How to use custom wmts as basemap ?

WMTS is one of the OGC services which we don't natively support. You could try loading the layer with REST API.

You can submit sample issues or creating a sample PR here. If you have general plugin questions, they'll get quicker response in [our unreal user forum](https://community.esri.com/t5/arcgis-maps-sdk-for-unreal-engine-questions/bd-p/arcgis-maps-sdk-unreal-engine-questions)
