### ISSUE TITLE
Cannot compile project on visual studio

### ISSUE THREAD

**Issue by pranaylamba777** [Esri/arcgis-maps-sdk-unreal-engine-samples#31]
When i compile the project on UE5 I get an error saying "compile from source". When I run it through Visual Studio, I get an error saying "MSB 3073 exited with code6".

**Comment by Krempeler** [comment]
Same problem. Running the sample project trough Visual Studio, I get 4 errors. 3 times C2039  "GetAPIkey" is no member of "UArcGISMapComponent"and MSB3073 the command "C:\Program Files\Epic Games\UE_5.1\Engine\Build\BatchFiles\Build.bat" sample_projectEditor Win64 Development -Project="D:\sample_project 5.1\sample_project.uproject" -WaitMutex -FromMsBuild" was exited with Code 6. I am running the latest version of Unreal Engine 5.1.1. I hope that I have not done anything obvious wrong.

**Comment by Jade-JadeH** [comment]
> Same problem. Running the sample project trough Visual Studio, I get 4 errors. 3 times C2039 "GetAPIkey" is no member of "UArcGISMapComponent"and MSB3073 the command "C:\Program Files\Epic Games\UE_5.1\Engine\Build\BatchFiles\Build.bat" sample_projectEditor Win64 Development -Project="D:\sample_project 5.1\sample_project.uproject" -WaitMutex -FromMsBuild" was exited with Code 6. I am running the latest version of Unreal Engine 5.1.1. I hope that I have not done anything obvious wrong.

Given the mutex error, do you have both unreal and VS opened?

**Comment by Jade-JadeH** [comment]
close due to inactivity
