### ISSUE TITLE
Unable to use ArcGIS Maps SDK for Unreal Engine   on version UE 5.1

### ISSUE THREAD

**Issue by bibinprathap** [Esri/arcgis-maps-sdk-unreal-engine-samples#32]
When i compile the project on UE5.1 I get an error saying "compile from source". When I run it through Visual Studio, I get an error saying

Build started...
1>------ Build started: Project: MyProject, Configuration: Development_Editor x64 ------
1>Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" MyProjectEditor Win64 Development -Project="C:\Users\User\Documents\Unreal Projects\MyProject\MyProject.uproject" -WaitMutex -FromMsBuild
1>Log file: C:\Users\User\AppData\Local\UnrealBuildTool\Log.txt
1>Building MyProjectEditor...
1>Using Visual Studio 2022 14.34.31935 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933) and Windows 10.0.22000.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Determining max actions to execute in parallel (2 physical cores, 4 logical cores)
1>  Executing up to 2 processes, one per physical core
1>  Requested 1.5 GB free memory per action, 2.2 GB available: limiting max parallel actions to 1
1>Building 8 actions with 1 process...
1>[1/8] Compile Module.ArcGISMapsSDK.13_of_13.cpp
1>C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ArcGISMapsSDK\Source\ArcGISMapsSDK\Private\Components\ArcGISMeshSceneProxy.cpp(159): warning C4996: 'FDynamicPrimitiveUniformBuffer::Set': Use version without bDrawsVelocity instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ArcGISMapsSDK\Source\ArcGISMapsSDK\Public\ArcGISMapsSDK\API\Unreal\ArcGISDataBuffer.h(185): error C4995: 'PLATFORM_COMPILER_HAS_IF_CONSTEXPR': name was marked as #pragma deprecated
1>C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ArcGISMapsSDK\Source\ArcGISMapsSDK\Private\Renderer\ArcGISRendererImpl.cpp(44): warning C4996: 'RHISupportsComputeShaders': This function is no longer in use and will be removed. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ArcGISMapsSDK\Source\ArcGISMapsSDK\Internal\ArcGISMapsSDK\Renderer\GPUComputing\ImageComposerShaders.h(29): warning C4996: 'RHISupportsComputeShaders': This function is no longer in use and will be removed. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ArcGISMapsSDK\Source\ArcGISMapsSDK\Internal\ArcGISMapsSDK\Renderer\GPUComputing\NormalMapGeneratorShaders.h(33): warning C4996: 'RHISupportsComputeShaders': This function is no longer in use and will be removed. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ArcGISMapsSDK\Source\ArcGISMapsSDK\Internal\ArcGISMapsSDK\Renderer\GPUComputing\NormalMapGeneratorShaders.h(59): warning C4996: 'RHISupportsComputeShaders': This function is no longer in use and will be removed. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ArcGISMapsSDK\Source\ArcGISMapsSDK\Private\Renderer\GPUComputing\TerrainOcclusionDepthMapRenderer.cpp(67): warning C4996: 'RHICreateTexture2D': FRHITexture2D is deprecated, please use RHICreateTexture(const FRHITextureCreateDesc&). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ArcGISMapsSDK\Source\ArcGISMapsSDK\Private\Renderer\GPUComputing\TerrainOcclusionDepthMapRenderer.cpp(373): warning C4996: 'RHICreateTexture2D': FRHITexture2D is deprecated, please use RHICreateTexture(const FRHITextureCreateDesc&). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>[2/8] Compile Module.ArcGISMapsSDK.10_of_13.cpp
1>C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ArcGISMapsSDK\Source\ArcGISMapsSDK\Public\ArcGISMapsSDK\API\Unreal\ArcGISDataBuffer.h(185): error C4995: 'PLATFORM_COMPILER_HAS_IF_CONSTEXPR': name was marked as #pragma deprecated
1>[3/8] Compile Module.ArcGISMapsSDK.11_of_13.cpp
1>C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ArcGISMapsSDK\Source\ArcGISMapsSDK\Public\ArcGISMapsSDK\API\Unreal\ArcGISDataBuffer.h(185): error C4995: 'PLATFORM_COMPILER_HAS_IF_CONSTEXPR': name was marked as #pragma deprecated
1>[4/8] Link UnrealEditor-ArcGISMapsSDK.lib cancelled
1>[5/8] Link UnrealEditor-ArcGISMapsSDK.dll cancelled
1>[6/8] Link UnrealEditor-ArcGISMapsSDKEditor.dll cancelled
1>[7/8] Link UnrealEditor-ArcGISSamples.dll cancelled
1>[8/8] WriteMetadata MyProjectEditor.target cancelled
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command ""C:\Program Files\Epic Games\UE_5.1\Engine\Build\BatchFiles\Build.bat" MyProjectEditor Win64 Development -Project="C:\Users\User\Documents\Unreal Projects\MyProject\MyProject.uproject" -WaitMutex -FromMsBuild" exited with code 6.
1>Done building project "MyProject.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 06:14.600 ==========

**Comment by mrnelson6** [comment]
We are resolving these issues in our next release. In the meantime you can use 5.0

**Comment by mrnelson6** [comment]
The new release is out. Want to try and see if its resolved

**Comment by Krempeler** [comment]
Still have this Problem

**Comment by Jade-JadeH** [comment]
@Krempeler Given the mutex error, do you have both unreal and VS opened?

**Comment by Jade-JadeH** [comment]
close due to inactivity
