### ISSUE TITLE
level cannot open with ue5.0.3

### ISSUE THREAD

**Issue by Rockflow** [Esri/arcgis-maps-sdk-unreal-engine-samples#38]
![image](https://user-images.githubusercontent.com/18820971/215403070-f5e25609-93df-453d-b425-766b1a974153.png)

the content cannot find the level

![image](https://user-images.githubusercontent.com/18820971/215403242-fe3542e3-90dc-417a-9119-c8d63995862a.png)

**Comment by NNNNemo** [comment]
I solved this problem by copying the umap files of the other branches.

**Comment by Jade-JadeH** [comment]
We fixed this.
