### ISSUE TITLE
Query a feature layer

### ISSUE THREAD

**Issue by wade460** [Esri/arcgis-maps-sdk-unreal-engine-samples#49]
In the sample code, feautrelayer.cpp. It used url to interface the feature layer (hosted) of ArcGIS Online.
Is there a way to read through the file? Or other way to interact. Because in my case I want to query the map without internet.

**Comment by mmgaw113** [comment]
As of right now, the only way to read through it would be via HTTP Request. If you have the json data local on your machine, I'm sure you can load that file through file streaming and read it that way. Please give this a try and let us know if it works! It would be great to have feature layer offline!
