### ISSUE TITLE
I can't build in VS

### ISSUE THREAD

**Issue by luigimux** [Esri/arcgis-maps-sdk-unreal-engine-samples#76]
I get the following error and I don't know how to fix it:

`Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB3073	The command ""C:\Program Files\Epic Games\UE_5.3\Engine\Build\BatchFiles\Build.bat" sample_projectEditor Win64 Development -Project="Z:\TEMP\arcgis_samples\sample_project\sample_project.uproject" -WaitMutex -FromMsBuild" exited with code 6.	sample_project	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets	44		
`

Thank you,
Luigi

**Comment by reramjiawan** [comment]
I have the same problem compiling with Visual Studio 2022 generates the above error output log.

**Comment by luigimux** [comment]
can anybody help please?

**Comment by reramjiawan** [comment]
@luigimux I managed to get it working by installing Unreal version 5.0.3 and following the solution of this forum post: https://community.gamedev.tv/t/compiling-issue-ue5-3/241963.

**Comment by luigimux** [comment]
hey @reramjiawan thank you for the pointer I will definitely test reverting the MSVC. So it works in 5.0.3 then.. I kind of suspected it.. today instead I managed to compile it if I take the 3DAttribute folder out of "Source"

![image](https://github.com/Esri/arcgis-maps-sdk-unreal-engine-samples/assets/14292886/d988fb4b-2d48-4e1b-93b6-00598a4402cc)

if I put it back it returns a long list of errors..

**Comment by luigimux** [comment]
I was able to compile in 5.1.1 but not in 5.2.1 nor 5.3.2
